from enum import Enum


class MessageTypeEnum(str, Enum):
    USER_JOIN = "USER_JOIN"
    USER_LEAVE = "USER_LEAVE"
    SUBMISSION_VERDICT_RETRIEVED = "SUBMISSION_VERDICT_RETRIEVED"
    SUBMISSION_VERDICT_PENDING = "SUBMISSION_VERDICT_PENDING"
    CODE_EDITOR_UPDATE = "CODE_EDITOR_UPDATE"
    CONTROL_TAKEN = "CONTROL_TAKEN"
    TRAINING_FINISHED = "TRAINING_FINISHED"
