stages:
  - deploy

deploy_production:
  image: docker:24.0
  stage: deploy
  only:
    - ci_cd
  script:
    - echo "Deploying to production..."
    - docker --version
    - docker-compose --version
    - cp .env_example .env
    - echo "Here we go" > /txt.txt
    - docker-compose up -d --build
