image: docker

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - echo "Run tests here"

deploy:
  stage: deploy
  only:
    - ci_cd
  script:
    - echo "Deploying to production..."
    - cp .env_example .env
    - docker-compose up -d --build
  environment: production
