stages:
  - test
  - deploy

pytest:
  stage: test
  script:
    - echo "Testing application"
    - docker build -t icpc-backend-testing -f Dockerfile_testing .
    - cp .env_example .env
    - docker run --network=icpc-backend --env-file .env --rm icpc-backend-testing

deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "Deploying to production..."
    - cp .env_example .env
    - ./docker-compose.sh prod
    - docker-compose up --build -d
