image: docker

services:
  docker:dind

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - ci_cd
  script:
    - echo "Deploying to production..."
    - docker --version
    - docker-compose --version
    - docker-compose up -d --build
  tags:
    - docker
