"""remove external_id from problem table

Revision ID: 48ad838a0586
Revises: e59b782349e2
Create Date: 2023-08-10 17:13:11.888229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ad838a0586'
down_revision = 'e59b782349e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq__problems__external_id', 'problems', type_='unique')
    op.drop_column('problems', 'external_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq__problems__external_id', 'problems', ['external_id'])
    # ### end Alembic commands ###
