"""switch text from varchar

Revision ID: a0961fe2b734
Revises: 028dcdfca773
Create Date: 2023-08-05 17:25:39.180959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0961fe2b734'
down_revision = '028dcdfca773'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__comments__id'), 'comments', ['id'])
    op.create_unique_constraint(op.f('uq__contest_trainings__id'), 'contest_trainings', ['id'])
    op.create_unique_constraint(op.f('uq__contests__id'), 'contests', ['id'])
    op.create_unique_constraint(op.f('uq__problems__id'), 'problems', ['id'])
    op.create_unique_constraint(op.f('uq__submissions__id'), 'submissions', ['id'])
    op.create_unique_constraint(op.f('uq__teams__id'), 'teams', ['id'])
    op.drop_constraint('fk__user_teams__user_id__users', 'user_teams', type_='foreignkey')
    op.drop_constraint('fk__user_teams__team_id__teams', 'user_teams', type_='foreignkey')
    op.create_foreign_key(op.f('fk__user_teams__team_id__teams'), 'user_teams', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk__user_teams__user_id__users'), 'user_teams', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq__users__id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__id'), 'users', type_='unique')
    op.drop_constraint(op.f('fk__user_teams__user_id__users'), 'user_teams', type_='foreignkey')
    op.drop_constraint(op.f('fk__user_teams__team_id__teams'), 'user_teams', type_='foreignkey')
    op.create_foreign_key('fk__user_teams__team_id__teams', 'user_teams', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('fk__user_teams__user_id__users', 'user_teams', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('uq__teams__id'), 'teams', type_='unique')
    op.drop_constraint(op.f('uq__submissions__id'), 'submissions', type_='unique')
    op.drop_constraint(op.f('uq__problems__id'), 'problems', type_='unique')
    op.drop_constraint(op.f('uq__contests__id'), 'contests', type_='unique')
    op.drop_constraint(op.f('uq__contest_trainings__id'), 'contest_trainings', type_='unique')
    op.drop_constraint(op.f('uq__comments__id'), 'comments', type_='unique')
    # ### end Alembic commands ###
