"""remove conent and add alias to problem table

Revision ID: e59b782349e2
Revises: 89f846b27aac
Create Date: 2023-08-10 13:18:04.864461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59b782349e2'
down_revision = '89f846b27aac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__comments__id'), 'comments', ['id'])
    op.create_unique_constraint(op.f('uq__contests__id'), 'contests', ['id'])
    op.add_column('problems', sa.Column('alias', sa.String(length=1), nullable=False))
    op.create_unique_constraint(op.f('uq__problems__id'), 'problems', ['id'])
    op.drop_column('problems', 'content')
    op.create_unique_constraint(op.f('uq__submissions__id'), 'submissions', ['id'])
    op.create_unique_constraint(op.f('uq__teams__id'), 'teams', ['id'])
    op.create_unique_constraint(op.f('uq__training_sessions__id'), 'training_sessions', ['id'])
    op.create_unique_constraint(op.f('uq__users__id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq__training_sessions__id'), 'training_sessions', type_='unique')
    op.drop_constraint(op.f('uq__teams__id'), 'teams', type_='unique')
    op.drop_constraint(op.f('uq__submissions__id'), 'submissions', type_='unique')
    op.add_column('problems', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq__problems__id'), 'problems', type_='unique')
    op.drop_column('problems', 'alias')
    op.drop_constraint(op.f('uq__contests__id'), 'contests', type_='unique')
    op.drop_constraint(op.f('uq__comments__id'), 'comments', type_='unique')
    # ### end Alembic commands ###
